# Generated by Django 2.0.6 on 2018-06-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='categories',
            field=models.CharField(default='all', max_length=200),
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.TextField(blank=True, default='all'),
        ),
    ]
